import pandas as pd
from collections import Counter

# Анализ данных
terms = [
    "Algorithm", "Data Structure", "Variable", "Function", "Class", "Object", "API",
    "Framework", "Library", "Syntax", "SQL", "NoSQL", "Index", "Transaction",
    "Normalization", "ACID", "ORM", "REST", "JSON", "XML", "HTTP", "HTTPS",
    "API Endpoint", "CI/CD", "Docker", "Kubernetes", "Git", "SSH", "Virtualization",
    "MVC", "Microservices", "Monolith", "API Gateway", "Load Balancer",
    "Authentication", "Authorization", "Encryption", "SQL Injection", "XSS",
    "Unit Test", "Integration Test", "Regression Test", "QA", "Agile", "Scrum",
    "Sprint", "MVP", "Backlog", "DNS", "TCP/IP", "Firewall", "CDN", "Big O",
    "Caching", "Optimization", "Scalability", "Debugging", "Refactoring",
    "Deployment", "Middleware", "SaaS", "Constant", "Method", "Parameter",
    "Argument", "Return Value", "Instance", "Constructor", "Destructor",
    "Interface", "Abstract Class", "Inheritance", "Polymorphism", "Encapsulation",
    "Abstraction", "Module", "Package", "Namespace", "Scope", "Global Variable",
    "Local Variable", "Compilation", "Interpretation", "JIT Compilation",
    "Bytecode", "Recursion", "Iteration", "Loop", "Conditional", "Data Type",
    "Primitive Type", "Reference Type", "Integer", "Float", "Double", "Boolean",
    "String", "Character", "Array", "List", "Tuple", "Dictionary", "Set", "Enum",
    "Pointer", "Null", "Undefined", "Linked List", "Stack", "Queue", "Deque",
    "Tree", "Binary Tree", "Binary Search Tree", "Graph", "Hash Table", "Heap",
    "Trie", "Bloom Filter", "RDBMS", "Database Schema", "Table", "Column", "Row",
    "Record", "Field", "Primary Key", "Foreign Key", "Composite Key", "Constraint",
    "Denormalization", "Entity", "Relationship", "SELECT", "INSERT", "UPDATE",
    "DELETE", "WHERE", "JOIN", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN",
    "FULL JOIN", "GROUP BY", "HAVING", "ORDER BY", "DISTINCT", "LIMIT", "OFFSET",
    "UNION", "VIEW", "STORED PROCEDURE", "TRIGGER", "FUNCTION", "RESTful", "YAML",
    "DOM", "CORS", "WebSocket", "Cookie", "Session", "Token", "JWT", "OAuth",
    "Single Page Application", "Progressive Web App", "Responsive Design", "UI",
    "UX", "UDP", "HTTP Status Code", "Load Balancing", "VPN", "SSL/TLS",
    "Certificate", "Domain", "Subdomain", "IP Address", "Port", "Proxy",
    "Gateway", "Router", "Switch", "Latency", "Bandwidth", "GET", "POST", "PUT",
    "PATCH", "DELETE", "HEAD", "OPTIONS", "Infrastructure as Code", "Monitoring",
    "Logging", "Container", "Image", "Orchestration", "MicroVM", "Serverless",
    "FaaS", "Repository", "Commit", "Branch", "Merge", "Rebase", "Clone", "Fork",
    "Pull Request", "Conflict", "Staging", "HEAD", "Tag", "Kanban", "Code Review",
    "Pair Programming", "Standup", "Retrospective", "User Story", "Epic", "Task",
    "Bug", "Feature", "Release", "Rollback", "Event-Driven Architecture",
    "Service Mesh", "CQRS", "Event Sourcing", "Hexagonal Architecture",
    "Clean Architecture", "DDD", "SOA", "N-Tier", "CSRF", "2FA", "MFA",
    "Hashing", "Salt", "Penetration Testing", "Vulnerability", "Zero Trust",
    "TDD", "Mock", "Stub", "Fixture", "Test Coverage", "E2E Test",
    "Performance Test", "Load Test", "Stress Test", "Smoke Test",
    "Acceptance Test", "Open Source", "Version Control", "Code Smell",
    "Technical Debt", "Design Pattern", "Anti-pattern", "KISS", "DRY", "YAGNI",
    "SOLID", "Blockchain", "AI", "Machine Learning", "Big Data", "IoT",
    "statement", "expression", "operator", "operand", "literal", "identifier",
    "keyword", "reserved word", "semicolon", "parentheses", "brackets", "braces",
    "quotes", "whitespace", "indentation", "control flow", "conditional", "loop",
    "iteration", "increment", "decrement", "break", "continue", "switch", "case",
    "default", "define", "declare", "implement", "invoke", "call", "pass",
    "return", "yield", "callback", "closure", "lambda", "arrow function",
    "exception", "error", "throw", "catch", "handle", "finally", "raise",
    "stack trace", "memory", "heap", "stack", "garbage collection", "allocate",
    "deallocate", "leak", "performance", "efficiency", "overhead", "instantiate",
    "instance", "property", "attribute", "field", "member", "access modifier",
    "public", "private", "protected", "static", "final", "sealed", "override",
    "overload", "extends", "implements", "super", "this", "self", "workspace",
    "playground", "sandbox", "boilerplate", "scaffolding", "blueprint",
    "linting", "formatting", "prettier", "cohesion", "coupling",
    "separation of concerns", "single responsibility", "dependency inversion",
    "inversion of control", "dependency injection", "coroutine", "fiber",
    "future", "promise", "observable", "stream", "pipeline", "middleware chain",
    "throughput", "bottleneck", "hotspot", "choke point", "fault tolerance",
    "graceful degradation", "circuit breaker", "blob", "payload", "envelope",
    "batch", "chunk", "shard", "replica", "snapshot", "checkpoint", "refactor",
    "restructure", "rearrange", "reorder", "reorganize", "streamline", "tweak",
    "fine-tune", "transform", "convert", "translate", "map", "reduce", "filter",
    "aggregate", "accumulate", "orchestrate", "coordinate", "synchronize",
    "reconcile", "replicate", "mirror", "propagate", "broadcast", "inspect",
    "examine", "analyze", "diagnose", "troubleshoot", "profile", "benchmark",
    "audit", "emit", "dispatch", "forward", "relay", "notify", "alert", "log",
    "trace", "performant", "responsive", "concurrent", "parallel",
    "asynchronous", "synchronous", "sequential", "iterative", "idle", "active",
    "dormant", "pending", "queued", "stale", "fresh", "cached", "trivial",
    "non-trivial", "straightforward", "intricate", "sophisticated", "elaborate",
    "convoluted", "resilient", "fault-tolerant", "robust", "fragile", "brittle",
    "durable", "persistent", "volatile", "sufficiently", "adequately",
    "appropriately", "properly", "thoroughly", "comprehensively", "partially",
    "fully", "elastic", "ephemeral", "stateful", "stateless", "immutable",
    "mutable", "cors", "csrf", "xss", "ssl", "tls", "cdn", "load balancer",
    "acid", "base", "cap theorem", "pessimistic locking", "optimistic locking",
    "deadlock", "livelock", "fixture", "mock", "stub", "spy", "assertion",
    "expectation", "coverage", "vulnerability", "exploit", "payload", "backdoor",
    "zero-day", "patch", "hotfix", "milestone", "deliverable", "artifact",
    "stakeholder", "requirement", "specification", "compliance",
    "it is worth noting", "keep in mind", "as follows", "as shown below",
    "as mentioned above", "refer to", "see also", "note that", "derivative",
    "integral", "vector", "matrix", "tensor", "scalar", "probability",
    "statistics", "implies", "equivalent", "contradiction", "tautology",
    "predicate", "quantifier", "i.e.", "e.g.", "etc.", "vs.", "approx.", "max",
    "min", "avg", "henceforth", "hitherto", "forthwith", "thence", "whilst",
    "mutable", "immutable", "nullable", "optional", "generic", "template",
    "type inference", "type casting", "coercion", "parse", "serialize",
    "deserialize", "marshal", "unmarshal", "iterate", "traverse", "enumerate",
    "slice", "concatenate", "append", "prepend", "pop", "push", "shift",
    "unshift", "splice", "query", "execute", "fetch", "retrieve", "persist",
    "flush", "commit", "rollback", "constraint", "cascade", "truncate", "upsert",
    "clause", "predicate", "alias", "wildcard", "subquery", "correlated subquery",
    "derived table", "cursor", "stored procedure", "trigger", "view",
    "materialized view", "document", "collection", "embed", "reference",
    "denormalize", "shard", "replica", "consistency", "availability",
    "partition tolerance", "render", "template", "component", "props", "state",
    "hook", "lifecycle", "mount", "unmount", "hydration", "request", "response",
    "headers", "payload", "endpoint", "route", "middleware", "interceptor",
    "proxy", "gateway", "latency", "throughput", "bandwidth", "vulnerability",
    "exploit", "patch", "sanitize", "validate", "escape", "hash", "encrypt",
    "decrypt", "sign", "verify", "provision", "deploy", "rollout", "scale",
    "orchestrate", "probe", "liveness", "readiness", "resilience", "redundancy",
    "stage", "unstaged", "untracked", "cherry-pick", "squash", "stash", "blame",
    "bisect", "assert", "expect", "mock", "stub", "spy", "fixture", "setup",
    "teardown", "coverage", "estimate", "track", "ticket", "milestone",
    "deadline", "blocker", "bottleneck", "throughput", "toggle", "enable",
    "disable", "trigger", "emit", "consume", "publish", "subscribe", "notify",
    "await", "resolve", "reject", "fulfill", "idempotent", "deterministic",
    "atomic", "race condition", "deadlock", "livelock", "starvation", "throttle",
    "debounce", "memoize", "curry", "compose", "robust", "scalable",
    "maintainable", "readable", "portable", "interoperable", "backward compatible",
    "deprecated", "legacy", "hence", "thus", "whereas", "thereby", "hereby",
    "forthwith", "aforementioned", "hereinafter", "it", "they", "we", "you",
    "this", "that", "these", "those", "which", "whose", "whom", "in", "on", "at",
    "by", "with", "without", "from", "to", "into", "onto", "between", "among",
    "through", "across", "behind", "above", "below", "under", "over", "before",
    "after", "during", "while", "until", "since", "about", "against", "among",
    "around", "beside", "beyond", "and", "or", "but", "because", "if", "unless",
    "although", "though", "even though", "whether", "while", "whereas", "do",
    "make", "create", "build", "use", "work", "run", "start", "stop", "begin",
    "end", "finish", "complete", "be", "have", "has", "had", "get", "become",
    "seem", "appear", "look", "give", "take", "put", "set", "let", "allow",
    "prevent", "avoid", "know", "understand", "think", "consider", "see", "look",
    "watch", "notice", "recognize", "set up", "break down", "carry out",
    "point out", "figure out", "turn on", "turn off", "look up", "look into",
    "important", "necessary", "essential", "crucial", "critical", "basic",
    "simple", "complex", "difficult", "easy", "possible", "impossible",
    "available", "unavailable", "efficient", "effective", "reliable", "stable",
    "unstable", "flexible", "rigid", "modular", "reusable", "better", "worse",
    "faster", "slower", "easier", "harder", "higher", "lower", "very", "quite",
    "rather", "almost", "nearly", "exactly", "precisely", "simply", "clearly",
    "obviously", "currently", "previously", "frequently", "rarely", "usually",
    "typically", "for example", "for instance", "such as", "in other words",
    "that is", "namely", "in particular", "especially", "specifically",
    "in order to", "so that", "due to", "because of", "as a result", "therefore",
    "thus", "hence", "compared to", "similar to", "different from", "unlike",
    "like", "as", "in fact", "actually", "indeed", "of course", "certainly",
    "firstly", "secondly", "finally", "in conclusion", "to summarize",
    "in summary", "however", "although", "despite", "in spite of", "nevertheless",
    "nonetheless", "how", "what", "when", "where", "why", "whether"
]

# Подсчет дубликатов
term_counts = Counter(terms)
duplicates = {term: count for term, count in term_counts.items() if count > 1}

print(f"Всего терминов: {len(terms)}")
print(f"Уникальных терминов: {len(set(terms))}")
print(f"Дубликатов найдено: {len(terms) - len(set(terms))}")
print(f"Количество дублирующихся терминов: {len(duplicates)}")

print("\nДублирующиеся термины:")
for i, (term, count) in enumerate(duplicates.items(), 1):
    print(f"{i:3}. {term} (встречается {count} раз)")